package kairon.observation.journal;

import kairon.observation.journal.event.session.*;
import kairon.observation.journal.event.travel.*;
import kairon.observation.journal.event.exploration.*;
import kairon.observation.journal.event.combat.*;
import kairon.observation.journal.event.ship.*;
import kairon.observation.journal.event.inventory.*;
import kairon.observation.journal.event.trade.*;
import kairon.observation.journal.event.mission.*;
import kairon.observation.journal.event.engineering.*;
import kairon.observation.journal.event.social.*;
import kairon.observation.journal.event.carrier.*;
import kairon.observation.journal.event.powerplay.*;
import kairon.observation.journal.event.onfoot.*;
import kairon.observation.journal.event.mining.*;
import kairon.observation.journal.event.colonisation.*;

import kairon.observation.journal.JournalEventObservation.RawJournalData;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.Function;

/**
 * Exact runtime mapping for the pinned jixxed/ed-journal-schemas catalogue.
 */
final class JournalEventCatalog {

    static final String PINNED_SCHEMA_REVISION =
            "33a8f35e81868b168b4bbd647b5e13dbd8de062a";

    private static final int EXPECTED_KNOWN_EVENT_COUNT = 272;
    private static final Map<String, Registration> REGISTRATIONS;
    private static final Set<String> KNOWN_EVENT_TYPES;

    static {
        Map<String, Registration> registrations = new LinkedHashMap<>();

        register(
                registrations,
                ClearSavedGame.EVENT_TYPE,
                ClearSavedGame.class,
                ClearSavedGame::new
        );
        register(
                registrations,
                Commander.EVENT_TYPE,
                Commander.class,
                Commander::new
        );
        register(
                registrations,
                Continued.EVENT_TYPE,
                Continued.class,
                Continued::new
        );
        register(
                registrations,
                Fileheader.EVENT_TYPE,
                Fileheader.class,
                Fileheader::new
        );
        register(
                registrations,
                LoadGame.EVENT_TYPE,
                LoadGame.class,
                LoadGame::new
        );
        register(
                registrations,
                Music.EVENT_TYPE,
                Music.class,
                Music::new
        );
        register(
                registrations,
                NewCommander.EVENT_TYPE,
                NewCommander.class,
                NewCommander::new
        );
        register(
                registrations,
                Progress.EVENT_TYPE,
                Progress.class,
                Progress::new
        );
        register(
                registrations,
                Promotion.EVENT_TYPE,
                Promotion.class,
                Promotion::new
        );
        register(
                registrations,
                Rank.EVENT_TYPE,
                Rank.class,
                Rank::new
        );
        register(
                registrations,
                Reputation.EVENT_TYPE,
                Reputation.class,
                Reputation::new
        );
        register(
                registrations,
                Screenshot.EVENT_TYPE,
                Screenshot.class,
                Screenshot::new
        );
        register(
                registrations,
                Shutdown.EVENT_TYPE,
                Shutdown.class,
                Shutdown::new
        );
        register(
                registrations,
                Statistics.EVENT_TYPE,
                Statistics.class,
                Statistics::new
        );
        register(
                registrations,
                ApproachBody.EVENT_TYPE,
                ApproachBody.class,
                ApproachBody::new
        );
        register(
                registrations,
                ApproachSettlement.EVENT_TYPE,
                ApproachSettlement.class,
                ApproachSettlement::new
        );
        register(
                registrations,
                BookDropship.EVENT_TYPE,
                BookDropship.class,
                BookDropship::new
        );
        register(
                registrations,
                BookTaxi.EVENT_TYPE,
                BookTaxi.class,
                BookTaxi::new
        );
        register(
                registrations,
                CancelDropship.EVENT_TYPE,
                CancelDropship.class,
                CancelDropship::new
        );
        register(
                registrations,
                CancelTaxi.EVENT_TYPE,
                CancelTaxi.class,
                CancelTaxi::new
        );
        register(
                registrations,
                Disembark.EVENT_TYPE,
                Disembark.class,
                Disembark::new
        );
        register(
                registrations,
                Docked.EVENT_TYPE,
                Docked.class,
                Docked::new
        );
        register(
                registrations,
                DockingCancelled.EVENT_TYPE,
                DockingCancelled.class,
                DockingCancelled::new
        );
        register(
                registrations,
                DockingDenied.EVENT_TYPE,
                DockingDenied.class,
                DockingDenied::new
        );
        register(
                registrations,
                DockingGranted.EVENT_TYPE,
                DockingGranted.class,
                DockingGranted::new
        );
        register(
                registrations,
                DockingRequested.EVENT_TYPE,
                DockingRequested.class,
                DockingRequested::new
        );
        register(
                registrations,
                DockingTimeout.EVENT_TYPE,
                DockingTimeout.class,
                DockingTimeout::new
        );
        register(
                registrations,
                DropshipDeploy.EVENT_TYPE,
                DropshipDeploy.class,
                DropshipDeploy::new
        );
        register(
                registrations,
                Embark.EVENT_TYPE,
                Embark.class,
                Embark::new
        );
        register(
                registrations,
                FSDJump.EVENT_TYPE,
                FSDJump.class,
                FSDJump::new
        );
        register(
                registrations,
                FSDTarget.EVENT_TYPE,
                FSDTarget.class,
                FSDTarget::new
        );
        register(
                registrations,
                FuelScoop.EVENT_TYPE,
                FuelScoop.class,
                FuelScoop::new
        );
        register(
                registrations,
                JetConeBoost.EVENT_TYPE,
                JetConeBoost.class,
                JetConeBoost::new
        );
        register(
                registrations,
                JetConeDamage.EVENT_TYPE,
                JetConeDamage.class,
                JetConeDamage::new
        );
        register(
                registrations,
                LeaveBody.EVENT_TYPE,
                LeaveBody.class,
                LeaveBody::new
        );
        register(
                registrations,
                Liftoff.EVENT_TYPE,
                Liftoff.class,
                Liftoff::new
        );
        register(
                registrations,
                Location.EVENT_TYPE,
                Location.class,
                Location::new
        );
        register(
                registrations,
                NavRoute.EVENT_TYPE,
                NavRoute.class,
                NavRoute::new
        );
        register(
                registrations,
                NavRouteClear.EVENT_TYPE,
                NavRouteClear.class,
                NavRouteClear::new
        );
        register(
                registrations,
                StartJump.EVENT_TYPE,
                StartJump.class,
                StartJump::new
        );
        register(
                registrations,
                SupercruiseDestinationDrop.EVENT_TYPE,
                SupercruiseDestinationDrop.class,
                SupercruiseDestinationDrop::new
        );
        register(
                registrations,
                SupercruiseEntry.EVENT_TYPE,
                SupercruiseEntry.class,
                SupercruiseEntry::new
        );
        register(
                registrations,
                SupercruiseExit.EVENT_TYPE,
                SupercruiseExit.class,
                SupercruiseExit::new
        );
        register(
                registrations,
                Touchdown.EVENT_TYPE,
                Touchdown.class,
                Touchdown::new
        );
        register(
                registrations,
                Undocked.EVENT_TYPE,
                Undocked.class,
                Undocked::new
        );
        register(
                registrations,
                USSDrop.EVENT_TYPE,
                USSDrop.class,
                USSDrop::new
        );
        register(
                registrations,
                VehicleSwitch.EVENT_TYPE,
                VehicleSwitch.class,
                VehicleSwitch::new
        );
        register(
                registrations,
                BuyExplorationData.EVENT_TYPE,
                BuyExplorationData.class,
                BuyExplorationData::new
        );
        register(
                registrations,
                CodexEntry.EVENT_TYPE,
                CodexEntry.class,
                CodexEntry::new
        );
        register(
                registrations,
                DatalinkScan.EVENT_TYPE,
                DatalinkScan.class,
                DatalinkScan::new
        );
        register(
                registrations,
                DatalinkVoucher.EVENT_TYPE,
                DatalinkVoucher.class,
                DatalinkVoucher::new
        );
        register(
                registrations,
                DataScanned.EVENT_TYPE,
                DataScanned.class,
                DataScanned::new
        );
        register(
                registrations,
                DiscoveryScan.EVENT_TYPE,
                DiscoveryScan.class,
                DiscoveryScan::new
        );
        register(
                registrations,
                FSSAllBodiesFound.EVENT_TYPE,
                FSSAllBodiesFound.class,
                FSSAllBodiesFound::new
        );
        register(
                registrations,
                FSSBodySignals.EVENT_TYPE,
                FSSBodySignals.class,
                FSSBodySignals::new
        );
        register(
                registrations,
                FSSDiscoveryScan.EVENT_TYPE,
                FSSDiscoveryScan.class,
                FSSDiscoveryScan::new
        );
        register(
                registrations,
                FSSSignalDiscovered.EVENT_TYPE,
                FSSSignalDiscovered.class,
                FSSSignalDiscovered::new
        );
        register(
                registrations,
                MultiSellExplorationData.EVENT_TYPE,
                MultiSellExplorationData.class,
                MultiSellExplorationData::new
        );
        register(
                registrations,
                NavBeaconScan.EVENT_TYPE,
                NavBeaconScan.class,
                NavBeaconScan::new
        );
        register(
                registrations,
                SAAScanComplete.EVENT_TYPE,
                SAAScanComplete.class,
                SAAScanComplete::new
        );
        register(
                registrations,
                SAASignalsFound.EVENT_TYPE,
                SAASignalsFound.class,
                SAASignalsFound::new
        );
        register(
                registrations,
                Scan.EVENT_TYPE,
                Scan.class,
                Scan::new
        );
        register(
                registrations,
                ScanBaryCentre.EVENT_TYPE,
                ScanBaryCentre.class,
                ScanBaryCentre::new
        );
        register(
                registrations,
                ScanOrganic.EVENT_TYPE,
                ScanOrganic.class,
                ScanOrganic::new
        );
        register(
                registrations,
                ScientificResearch.EVENT_TYPE,
                ScientificResearch.class,
                ScientificResearch::new
        );
        register(
                registrations,
                SellExplorationData.EVENT_TYPE,
                SellExplorationData.class,
                SellExplorationData::new
        );
        register(
                registrations,
                SellOrganicData.EVENT_TYPE,
                SellOrganicData.class,
                SellOrganicData::new
        );
        register(
                registrations,
                Bounty.EVENT_TYPE,
                Bounty.class,
                Bounty::new
        );
        register(
                registrations,
                CapShipBond.EVENT_TYPE,
                CapShipBond.class,
                CapShipBond::new
        );
        register(
                registrations,
                CockpitBreached.EVENT_TYPE,
                CockpitBreached.class,
                CockpitBreached::new
        );
        register(
                registrations,
                CommitCrime.EVENT_TYPE,
                CommitCrime.class,
                CommitCrime::new
        );
        register(
                registrations,
                CrimeVictim.EVENT_TYPE,
                CrimeVictim.class,
                CrimeVictim::new
        );
        register(
                registrations,
                Died.EVENT_TYPE,
                Died.class,
                Died::new
        );
        register(
                registrations,
                EscapeInterdiction.EVENT_TYPE,
                EscapeInterdiction.class,
                EscapeInterdiction::new
        );
        register(
                registrations,
                FactionKillBond.EVENT_TYPE,
                FactionKillBond.class,
                FactionKillBond::new
        );
        register(
                registrations,
                HeatDamage.EVENT_TYPE,
                HeatDamage.class,
                HeatDamage::new
        );
        register(
                registrations,
                HeatWarning.EVENT_TYPE,
                HeatWarning.class,
                HeatWarning::new
        );
        register(
                registrations,
                HullDamage.EVENT_TYPE,
                HullDamage.class,
                HullDamage::new
        );
        register(
                registrations,
                Interdicted.EVENT_TYPE,
                Interdicted.class,
                Interdicted::new
        );
        register(
                registrations,
                Interdiction.EVENT_TYPE,
                Interdiction.class,
                Interdiction::new
        );
        register(
                registrations,
                PayBounties.EVENT_TYPE,
                PayBounties.class,
                PayBounties::new
        );
        register(
                registrations,
                PayFines.EVENT_TYPE,
                PayFines.class,
                PayFines::new
        );
        register(
                registrations,
                PVPKill.EVENT_TYPE,
                PVPKill.class,
                PVPKill::new
        );
        register(
                registrations,
                Resurrect.EVENT_TYPE,
                Resurrect.class,
                Resurrect::new
        );
        register(
                registrations,
                Scanned.EVENT_TYPE,
                Scanned.class,
                Scanned::new
        );
        register(
                registrations,
                SelfDestruct.EVENT_TYPE,
                SelfDestruct.class,
                SelfDestruct::new
        );
        register(
                registrations,
                ShieldState.EVENT_TYPE,
                ShieldState.class,
                ShieldState::new
        );
        register(
                registrations,
                ShipTargeted.EVENT_TYPE,
                ShipTargeted.class,
                ShipTargeted::new
        );
        register(
                registrations,
                SystemsShutdown.EVENT_TYPE,
                SystemsShutdown.class,
                SystemsShutdown::new
        );
        register(
                registrations,
                UnderAttack.EVENT_TYPE,
                UnderAttack.class,
                UnderAttack::new
        );
        register(
                registrations,
                AfmuRepairs.EVENT_TYPE,
                AfmuRepairs.class,
                AfmuRepairs::new
        );
        register(
                registrations,
                BuyAmmo.EVENT_TYPE,
                BuyAmmo.class,
                BuyAmmo::new
        );
        register(
                registrations,
                BuyDrones.EVENT_TYPE,
                BuyDrones.class,
                BuyDrones::new
        );
        register(
                registrations,
                ClearImpound.EVENT_TYPE,
                ClearImpound.class,
                ClearImpound::new
        );
        register(
                registrations,
                DockFighter.EVENT_TYPE,
                DockFighter.class,
                DockFighter::new
        );
        register(
                registrations,
                DockSRV.EVENT_TYPE,
                DockSRV.class,
                DockSRV::new
        );
        register(
                registrations,
                FetchRemoteModule.EVENT_TYPE,
                FetchRemoteModule.class,
                FetchRemoteModule::new
        );
        register(
                registrations,
                FighterDestroyed.EVENT_TYPE,
                FighterDestroyed.class,
                FighterDestroyed::new
        );
        register(
                registrations,
                FighterRebuilt.EVENT_TYPE,
                FighterRebuilt.class,
                FighterRebuilt::new
        );
        register(
                registrations,
                LaunchDrone.EVENT_TYPE,
                LaunchDrone.class,
                LaunchDrone::new
        );
        register(
                registrations,
                LaunchFighter.EVENT_TYPE,
                LaunchFighter.class,
                LaunchFighter::new
        );
        register(
                registrations,
                LaunchSRV.EVENT_TYPE,
                LaunchSRV.class,
                LaunchSRV::new
        );
        register(
                registrations,
                Loadout.EVENT_TYPE,
                Loadout.class,
                Loadout::new
        );
        register(
                registrations,
                LoadoutEquipModule.EVENT_TYPE,
                LoadoutEquipModule.class,
                LoadoutEquipModule::new
        );
        register(
                registrations,
                LoadoutRemoveModule.EVENT_TYPE,
                LoadoutRemoveModule.class,
                LoadoutRemoveModule::new
        );
        register(
                registrations,
                MassModuleStore.EVENT_TYPE,
                MassModuleStore.class,
                MassModuleStore::new
        );
        register(
                registrations,
                ModuleBuy.EVENT_TYPE,
                ModuleBuy.class,
                ModuleBuy::new
        );
        register(
                registrations,
                ModuleBuyAndStore.EVENT_TYPE,
                ModuleBuyAndStore.class,
                ModuleBuyAndStore::new
        );
        register(
                registrations,
                ModuleInfo.EVENT_TYPE,
                ModuleInfo.class,
                ModuleInfo::new
        );
        register(
                registrations,
                ModuleRetrieve.EVENT_TYPE,
                ModuleRetrieve.class,
                ModuleRetrieve::new
        );
        register(
                registrations,
                ModuleSell.EVENT_TYPE,
                ModuleSell.class,
                ModuleSell::new
        );
        register(
                registrations,
                ModuleSellRemote.EVENT_TYPE,
                ModuleSellRemote.class,
                ModuleSellRemote::new
        );
        register(
                registrations,
                ModuleStore.EVENT_TYPE,
                ModuleStore.class,
                ModuleStore::new
        );
        register(
                registrations,
                ModuleSwap.EVENT_TYPE,
                ModuleSwap.class,
                ModuleSwap::new
        );
        register(
                registrations,
                Outfitting.EVENT_TYPE,
                Outfitting.class,
                Outfitting::new
        );
        register(
                registrations,
                RebootRepair.EVENT_TYPE,
                RebootRepair.class,
                RebootRepair::new
        );
        register(
                registrations,
                RefuelAll.EVENT_TYPE,
                RefuelAll.class,
                RefuelAll::new
        );
        register(
                registrations,
                RefuelPartial.EVENT_TYPE,
                RefuelPartial.class,
                RefuelPartial::new
        );
        register(
                registrations,
                Repair.EVENT_TYPE,
                Repair.class,
                Repair::new
        );
        register(
                registrations,
                RepairAll.EVENT_TYPE,
                RepairAll.class,
                RepairAll::new
        );
        register(
                registrations,
                RepairDrone.EVENT_TYPE,
                RepairDrone.class,
                RepairDrone::new
        );
        register(
                registrations,
                ReservoirReplenished.EVENT_TYPE,
                ReservoirReplenished.class,
                ReservoirReplenished::new
        );
        register(
                registrations,
                RestockVehicle.EVENT_TYPE,
                RestockVehicle.class,
                RestockVehicle::new
        );
        register(
                registrations,
                Resupply.EVENT_TYPE,
                Resupply.class,
                Resupply::new
        );
        register(
                registrations,
                SellDrones.EVENT_TYPE,
                SellDrones.class,
                SellDrones::new
        );
        register(
                registrations,
                SellShipOnRebuy.EVENT_TYPE,
                SellShipOnRebuy.class,
                SellShipOnRebuy::new
        );
        register(
                registrations,
                SetUserShipName.EVENT_TYPE,
                SetUserShipName.class,
                SetUserShipName::new
        );
        register(
                registrations,
                ShipRedeemed.EVENT_TYPE,
                ShipRedeemed.class,
                ShipRedeemed::new
        );
        register(
                registrations,
                Shipyard.EVENT_TYPE,
                Shipyard.class,
                Shipyard::new
        );
        register(
                registrations,
                ShipyardBankDeposit.EVENT_TYPE,
                ShipyardBankDeposit.class,
                ShipyardBankDeposit::new
        );
        register(
                registrations,
                ShipyardBuy.EVENT_TYPE,
                ShipyardBuy.class,
                ShipyardBuy::new
        );
        register(
                registrations,
                ShipyardNew.EVENT_TYPE,
                ShipyardNew.class,
                ShipyardNew::new
        );
        register(
                registrations,
                ShipyardRedeem.EVENT_TYPE,
                ShipyardRedeem.class,
                ShipyardRedeem::new
        );
        register(
                registrations,
                ShipyardSell.EVENT_TYPE,
                ShipyardSell.class,
                ShipyardSell::new
        );
        register(
                registrations,
                ShipyardSwap.EVENT_TYPE,
                ShipyardSwap.class,
                ShipyardSwap::new
        );
        register(
                registrations,
                ShipyardTransfer.EVENT_TYPE,
                ShipyardTransfer.class,
                ShipyardTransfer::new
        );
        register(
                registrations,
                SRVDestroyed.EVENT_TYPE,
                SRVDestroyed.class,
                SRVDestroyed::new
        );
        register(
                registrations,
                StoredModules.EVENT_TYPE,
                StoredModules.class,
                StoredModules::new
        );
        register(
                registrations,
                StoredShips.EVENT_TYPE,
                StoredShips.class,
                StoredShips::new
        );
        register(
                registrations,
                Cargo.EVENT_TYPE,
                Cargo.class,
                Cargo::new
        );
        register(
                registrations,
                CargoTransfer.EVENT_TYPE,
                CargoTransfer.class,
                CargoTransfer::new
        );
        register(
                registrations,
                CollectCargo.EVENT_TYPE,
                CollectCargo.class,
                CollectCargo::new
        );
        register(
                registrations,
                EjectCargo.EVENT_TYPE,
                EjectCargo.class,
                EjectCargo::new
        );
        register(
                registrations,
                MaterialCollected.EVENT_TYPE,
                MaterialCollected.class,
                MaterialCollected::new
        );
        register(
                registrations,
                MaterialDiscarded.EVENT_TYPE,
                MaterialDiscarded.class,
                MaterialDiscarded::new
        );
        register(
                registrations,
                MaterialDiscovered.EVENT_TYPE,
                MaterialDiscovered.class,
                MaterialDiscovered::new
        );
        register(
                registrations,
                Materials.EVENT_TYPE,
                Materials.class,
                Materials::new
        );
        register(
                registrations,
                BuyTradeData.EVENT_TYPE,
                BuyTradeData.class,
                BuyTradeData::new
        );
        register(
                registrations,
                Market.EVENT_TYPE,
                Market.class,
                Market::new
        );
        register(
                registrations,
                MarketBuy.EVENT_TYPE,
                MarketBuy.class,
                MarketBuy::new
        );
        register(
                registrations,
                MarketID.EVENT_TYPE,
                MarketID.class,
                MarketID::new
        );
        register(
                registrations,
                MarketSell.EVENT_TYPE,
                MarketSell.class,
                MarketSell::new
        );
        register(
                registrations,
                RedeemVoucher.EVENT_TYPE,
                RedeemVoucher.class,
                RedeemVoucher::new
        );
        register(
                registrations,
                SearchAndRescue.EVENT_TYPE,
                SearchAndRescue.class,
                SearchAndRescue::new
        );
        register(
                registrations,
                CargoDepot.EVENT_TYPE,
                CargoDepot.class,
                CargoDepot::new
        );
        register(
                registrations,
                CommunityGoal.EVENT_TYPE,
                CommunityGoal.class,
                CommunityGoal::new
        );
        register(
                registrations,
                CommunityGoalDiscard.EVENT_TYPE,
                CommunityGoalDiscard.class,
                CommunityGoalDiscard::new
        );
        register(
                registrations,
                CommunityGoalJoin.EVENT_TYPE,
                CommunityGoalJoin.class,
                CommunityGoalJoin::new
        );
        register(
                registrations,
                CommunityGoalReward.EVENT_TYPE,
                CommunityGoalReward.class,
                CommunityGoalReward::new
        );
        register(
                registrations,
                MissionAbandoned.EVENT_TYPE,
                MissionAbandoned.class,
                MissionAbandoned::new
        );
        register(
                registrations,
                MissionAccepted.EVENT_TYPE,
                MissionAccepted.class,
                MissionAccepted::new
        );
        register(
                registrations,
                MissionCompleted.EVENT_TYPE,
                MissionCompleted.class,
                MissionCompleted::new
        );
        register(
                registrations,
                MissionFailed.EVENT_TYPE,
                MissionFailed.class,
                MissionFailed::new
        );
        register(
                registrations,
                MissionRedirected.EVENT_TYPE,
                MissionRedirected.class,
                MissionRedirected::new
        );
        register(
                registrations,
                Missions.EVENT_TYPE,
                Missions.class,
                Missions::new
        );
        register(
                registrations,
                Passengers.EVENT_TYPE,
                Passengers.class,
                Passengers::new
        );
        register(
                registrations,
                EngineerContribution.EVENT_TYPE,
                EngineerContribution.class,
                EngineerContribution::new
        );
        register(
                registrations,
                EngineerCraft.EVENT_TYPE,
                EngineerCraft.class,
                EngineerCraft::new
        );
        register(
                registrations,
                EngineerLegacyConvert.EVENT_TYPE,
                EngineerLegacyConvert.class,
                EngineerLegacyConvert::new
        );
        register(
                registrations,
                EngineerProgress.EVENT_TYPE,
                EngineerProgress.class,
                EngineerProgress::new
        );
        register(
                registrations,
                MaterialTrade.EVENT_TYPE,
                MaterialTrade.class,
                MaterialTrade::new
        );
        register(
                registrations,
                Synthesis.EVENT_TYPE,
                Synthesis.class,
                Synthesis::new
        );
        register(
                registrations,
                TechnologyBroker.EVENT_TYPE,
                TechnologyBroker.class,
                TechnologyBroker::new
        );
        register(
                registrations,
                AppliedToSquadron.EVENT_TYPE,
                AppliedToSquadron.class,
                AppliedToSquadron::new
        );
        register(
                registrations,
                CancelledSquadronApplication.EVENT_TYPE,
                CancelledSquadronApplication.class,
                CancelledSquadronApplication::new
        );
        register(
                registrations,
                ChangeCrewRole.EVENT_TYPE,
                ChangeCrewRole.class,
                ChangeCrewRole::new
        );
        register(
                registrations,
                CrewAssign.EVENT_TYPE,
                CrewAssign.class,
                CrewAssign::new
        );
        register(
                registrations,
                CrewFire.EVENT_TYPE,
                CrewFire.class,
                CrewFire::new
        );
        register(
                registrations,
                CrewHire.EVENT_TYPE,
                CrewHire.class,
                CrewHire::new
        );
        register(
                registrations,
                CrewLaunchFighter.EVENT_TYPE,
                CrewLaunchFighter.class,
                CrewLaunchFighter::new
        );
        register(
                registrations,
                CrewMemberJoins.EVENT_TYPE,
                CrewMemberJoins.class,
                CrewMemberJoins::new
        );
        register(
                registrations,
                CrewMemberQuits.EVENT_TYPE,
                CrewMemberQuits.class,
                CrewMemberQuits::new
        );
        register(
                registrations,
                CrewMemberRoleChange.EVENT_TYPE,
                CrewMemberRoleChange.class,
                CrewMemberRoleChange::new
        );
        register(
                registrations,
                DisbandedSquadron.EVENT_TYPE,
                DisbandedSquadron.class,
                DisbandedSquadron::new
        );
        register(
                registrations,
                EndCrewSession.EVENT_TYPE,
                EndCrewSession.class,
                EndCrewSession::new
        );
        register(
                registrations,
                Friends.EVENT_TYPE,
                Friends.class,
                Friends::new
        );
        register(
                registrations,
                InvitedToSquadron.EVENT_TYPE,
                InvitedToSquadron.class,
                InvitedToSquadron::new
        );
        register(
                registrations,
                JoinACrew.EVENT_TYPE,
                JoinACrew.class,
                JoinACrew::new
        );
        register(
                registrations,
                JoinedSquadron.EVENT_TYPE,
                JoinedSquadron.class,
                JoinedSquadron::new
        );
        register(
                registrations,
                KickCrewMember.EVENT_TYPE,
                KickCrewMember.class,
                KickCrewMember::new
        );
        register(
                registrations,
                KickedFromSquadron.EVENT_TYPE,
                KickedFromSquadron.class,
                KickedFromSquadron::new
        );
        register(
                registrations,
                LeftSquadron.EVENT_TYPE,
                LeftSquadron.class,
                LeftSquadron::new
        );
        register(
                registrations,
                NpcCrewPaidWage.EVENT_TYPE,
                NpcCrewPaidWage.class,
                NpcCrewPaidWage::new
        );
        register(
                registrations,
                NpcCrewRank.EVENT_TYPE,
                NpcCrewRank.class,
                NpcCrewRank::new
        );
        register(
                registrations,
                QuitACrew.EVENT_TYPE,
                QuitACrew.class,
                QuitACrew::new
        );
        register(
                registrations,
                ReceiveText.EVENT_TYPE,
                ReceiveText.class,
                ReceiveText::new
        );
        register(
                registrations,
                SendText.EVENT_TYPE,
                SendText.class,
                SendText::new
        );
        register(
                registrations,
                SharedBookmarkToSquadron.EVENT_TYPE,
                SharedBookmarkToSquadron.class,
                SharedBookmarkToSquadron::new
        );
        register(
                registrations,
                SquadronApplicationApproved.EVENT_TYPE,
                SquadronApplicationApproved.class,
                SquadronApplicationApproved::new
        );
        register(
                registrations,
                SquadronApplicationRejected.EVENT_TYPE,
                SquadronApplicationRejected.class,
                SquadronApplicationRejected::new
        );
        register(
                registrations,
                SquadronCreated.EVENT_TYPE,
                SquadronCreated.class,
                SquadronCreated::new
        );
        register(
                registrations,
                SquadronDemotion.EVENT_TYPE,
                SquadronDemotion.class,
                SquadronDemotion::new
        );
        register(
                registrations,
                SquadronPromotion.EVENT_TYPE,
                SquadronPromotion.class,
                SquadronPromotion::new
        );
        register(
                registrations,
                SquadronStartup.EVENT_TYPE,
                SquadronStartup.class,
                SquadronStartup::new
        );
        register(
                registrations,
                WingAdd.EVENT_TYPE,
                WingAdd.class,
                WingAdd::new
        );
        register(
                registrations,
                WingInvite.EVENT_TYPE,
                WingInvite.class,
                WingInvite::new
        );
        register(
                registrations,
                WingJoin.EVENT_TYPE,
                WingJoin.class,
                WingJoin::new
        );
        register(
                registrations,
                WingLeave.EVENT_TYPE,
                WingLeave.class,
                WingLeave::new
        );
        register(
                registrations,
                CarrierBankTransfer.EVENT_TYPE,
                CarrierBankTransfer.class,
                CarrierBankTransfer::new
        );
        register(
                registrations,
                CarrierBuy.EVENT_TYPE,
                CarrierBuy.class,
                CarrierBuy::new
        );
        register(
                registrations,
                CarrierCancelDecommission.EVENT_TYPE,
                CarrierCancelDecommission.class,
                CarrierCancelDecommission::new
        );
        register(
                registrations,
                CarrierCrewServices.EVENT_TYPE,
                CarrierCrewServices.class,
                CarrierCrewServices::new
        );
        register(
                registrations,
                CarrierDecommission.EVENT_TYPE,
                CarrierDecommission.class,
                CarrierDecommission::new
        );
        register(
                registrations,
                CarrierDepositFuel.EVENT_TYPE,
                CarrierDepositFuel.class,
                CarrierDepositFuel::new
        );
        register(
                registrations,
                CarrierDockingPermission.EVENT_TYPE,
                CarrierDockingPermission.class,
                CarrierDockingPermission::new
        );
        register(
                registrations,
                CarrierFinance.EVENT_TYPE,
                CarrierFinance.class,
                CarrierFinance::new
        );
        register(
                registrations,
                CarrierJump.EVENT_TYPE,
                CarrierJump.class,
                CarrierJump::new
        );
        register(
                registrations,
                CarrierJumpCancelled.EVENT_TYPE,
                CarrierJumpCancelled.class,
                CarrierJumpCancelled::new
        );
        register(
                registrations,
                CarrierJumpRequest.EVENT_TYPE,
                CarrierJumpRequest.class,
                CarrierJumpRequest::new
        );
        register(
                registrations,
                CarrierLocation.EVENT_TYPE,
                CarrierLocation.class,
                CarrierLocation::new
        );
        register(
                registrations,
                CarrierModulePack.EVENT_TYPE,
                CarrierModulePack.class,
                CarrierModulePack::new
        );
        register(
                registrations,
                CarrierNameChange.EVENT_TYPE,
                CarrierNameChange.class,
                CarrierNameChange::new
        );
        register(
                registrations,
                CarrierShipPack.EVENT_TYPE,
                CarrierShipPack.class,
                CarrierShipPack::new
        );
        register(
                registrations,
                CarrierStats.EVENT_TYPE,
                CarrierStats.class,
                CarrierStats::new
        );
        register(
                registrations,
                CarrierTradeOrder.EVENT_TYPE,
                CarrierTradeOrder.class,
                CarrierTradeOrder::new
        );
        register(
                registrations,
                FCMaterials.EVENT_TYPE,
                FCMaterials.class,
                FCMaterials::new
        );
        register(
                registrations,
                Powerplay.EVENT_TYPE,
                Powerplay.class,
                Powerplay::new
        );
        register(
                registrations,
                PowerplayCollect.EVENT_TYPE,
                PowerplayCollect.class,
                PowerplayCollect::new
        );
        register(
                registrations,
                PowerplayDefect.EVENT_TYPE,
                PowerplayDefect.class,
                PowerplayDefect::new
        );
        register(
                registrations,
                PowerplayDeliver.EVENT_TYPE,
                PowerplayDeliver.class,
                PowerplayDeliver::new
        );
        register(
                registrations,
                PowerplayFastTrack.EVENT_TYPE,
                PowerplayFastTrack.class,
                PowerplayFastTrack::new
        );
        register(
                registrations,
                PowerplayJoin.EVENT_TYPE,
                PowerplayJoin.class,
                PowerplayJoin::new
        );
        register(
                registrations,
                PowerplayLeave.EVENT_TYPE,
                PowerplayLeave.class,
                PowerplayLeave::new
        );
        register(
                registrations,
                PowerplayMerits.EVENT_TYPE,
                PowerplayMerits.class,
                PowerplayMerits::new
        );
        register(
                registrations,
                PowerplayRank.EVENT_TYPE,
                PowerplayRank.class,
                PowerplayRank::new
        );
        register(
                registrations,
                PowerplaySalary.EVENT_TYPE,
                PowerplaySalary.class,
                PowerplaySalary::new
        );
        register(
                registrations,
                PowerplayVote.EVENT_TYPE,
                PowerplayVote.class,
                PowerplayVote::new
        );
        register(
                registrations,
                PowerplayVoucher.EVENT_TYPE,
                PowerplayVoucher.class,
                PowerplayVoucher::new
        );
        register(
                registrations,
                Backpack.EVENT_TYPE,
                Backpack.class,
                Backpack::new
        );
        register(
                registrations,
                BackpackChange.EVENT_TYPE,
                BackpackChange.class,
                BackpackChange::new
        );
        register(
                registrations,
                BuyMicroResources.EVENT_TYPE,
                BuyMicroResources.class,
                BuyMicroResources::new
        );
        register(
                registrations,
                BuySuit.EVENT_TYPE,
                BuySuit.class,
                BuySuit::new
        );
        register(
                registrations,
                BuyWeapon.EVENT_TYPE,
                BuyWeapon.class,
                BuyWeapon::new
        );
        register(
                registrations,
                CollectItems.EVENT_TYPE,
                CollectItems.class,
                CollectItems::new
        );
        register(
                registrations,
                CreateSuitLoadout.EVENT_TYPE,
                CreateSuitLoadout.class,
                CreateSuitLoadout::new
        );
        register(
                registrations,
                DeleteSuitLoadout.EVENT_TYPE,
                DeleteSuitLoadout.class,
                DeleteSuitLoadout::new
        );
        register(
                registrations,
                DeliverPowerMicroResources.EVENT_TYPE,
                DeliverPowerMicroResources.class,
                DeliverPowerMicroResources::new
        );
        register(
                registrations,
                DropItems.EVENT_TYPE,
                DropItems.class,
                DropItems::new
        );
        register(
                registrations,
                HoloscreenHacked.EVENT_TYPE,
                HoloscreenHacked.class,
                HoloscreenHacked::new
        );
        register(
                registrations,
                RenameSuitLoadout.EVENT_TYPE,
                RenameSuitLoadout.class,
                RenameSuitLoadout::new
        );
        register(
                registrations,
                RequestPowerMicroResources.EVENT_TYPE,
                RequestPowerMicroResources.class,
                RequestPowerMicroResources::new
        );
        register(
                registrations,
                SellMicroResources.EVENT_TYPE,
                SellMicroResources.class,
                SellMicroResources::new
        );
        register(
                registrations,
                SellSuit.EVENT_TYPE,
                SellSuit.class,
                SellSuit::new
        );
        register(
                registrations,
                SellWeapon.EVENT_TYPE,
                SellWeapon.class,
                SellWeapon::new
        );
        register(
                registrations,
                ShipLocker.EVENT_TYPE,
                ShipLocker.class,
                ShipLocker::new
        );
        register(
                registrations,
                ShipLockerMaterials.EVENT_TYPE,
                ShipLockerMaterials.class,
                ShipLockerMaterials::new
        );
        register(
                registrations,
                SuitLoadout.EVENT_TYPE,
                SuitLoadout.class,
                SuitLoadout::new
        );
        register(
                registrations,
                SwitchSuitLoadout.EVENT_TYPE,
                SwitchSuitLoadout.class,
                SwitchSuitLoadout::new
        );
        register(
                registrations,
                TradeMicroResources.EVENT_TYPE,
                TradeMicroResources.class,
                TradeMicroResources::new
        );
        register(
                registrations,
                TransferMicroResources.EVENT_TYPE,
                TransferMicroResources.class,
                TransferMicroResources::new
        );
        register(
                registrations,
                UpgradeSuit.EVENT_TYPE,
                UpgradeSuit.class,
                UpgradeSuit::new
        );
        register(
                registrations,
                UpgradeWeapon.EVENT_TYPE,
                UpgradeWeapon.class,
                UpgradeWeapon::new
        );
        register(
                registrations,
                UseConsumable.EVENT_TYPE,
                UseConsumable.class,
                UseConsumable::new
        );
        register(
                registrations,
                AsteroidCracked.EVENT_TYPE,
                AsteroidCracked.class,
                AsteroidCracked::new
        );
        register(
                registrations,
                MiningRefined.EVENT_TYPE,
                MiningRefined.class,
                MiningRefined::new
        );
        register(
                registrations,
                ProspectedAsteroid.EVENT_TYPE,
                ProspectedAsteroid.class,
                ProspectedAsteroid::new
        );
        register(
                registrations,
                ColonisationBeaconDeployed.EVENT_TYPE,
                ColonisationBeaconDeployed.class,
                ColonisationBeaconDeployed::new
        );
        register(
                registrations,
                ColonisationConstructionDepot.EVENT_TYPE,
                ColonisationConstructionDepot.class,
                ColonisationConstructionDepot::new
        );
        register(
                registrations,
                ColonisationContribution.EVENT_TYPE,
                ColonisationContribution.class,
                ColonisationContribution::new
        );
        register(
                registrations,
                ColonisationSystemClaim.EVENT_TYPE,
                ColonisationSystemClaim.class,
                ColonisationSystemClaim::new
        );
        register(
                registrations,
                ColonisationSystemClaimRelease.EVENT_TYPE,
                ColonisationSystemClaimRelease.class,
                ColonisationSystemClaimRelease::new
        );
        register(
                registrations,
                CompleteConstruction.EVENT_TYPE,
                CompleteConstruction.class,
                CompleteConstruction::new
        );
        if (registrations.size() != EXPECTED_KNOWN_EVENT_COUNT) {
            throw new ExceptionInInitializerError(
                    "Expected " + EXPECTED_KNOWN_EVENT_COUNT
                            + " known journal event types but registered "
                            + registrations.size()
            );
        }

        REGISTRATIONS = Map.copyOf(registrations);
        KNOWN_EVENT_TYPES =
                Collections.unmodifiableSet(
                        new TreeSet<>(registrations.keySet())
                );
    }

    private JournalEventCatalog() {
    }

    static Set<String> knownEventTypes() {
        return KNOWN_EVENT_TYPES;
    }

    static JournalEventObservation create(RawJournalData raw) {
        raw = Objects.requireNonNull(raw, "raw");
        Registration registration =
                raw.optionalEventType().map(REGISTRATIONS::get).orElse(null);
        return registration == null
                ? new UnknownJournalEvent(raw)
                : registration.factory().apply(raw);
    }

    static Class<? extends JournalEventObservation> payloadTypeFor(
            String eventType
    ) {
        Registration registration =
                REGISTRATIONS.get(
                        Objects.requireNonNull(eventType, "eventType")
                );
        return registration == null
                ? UnknownJournalEvent.class
                : registration.payloadType();
    }

    static boolean isKnownEventType(String eventType) {
        return REGISTRATIONS.containsKey(
                Objects.requireNonNull(eventType, "eventType")
        );
    }

    private static <T extends JournalEventObservation> void register(
            Map<String, Registration> registrations,
            String eventType,
            Class<T> payloadType,
            Function<RawJournalData, T> factory
    ) {
        Objects.requireNonNull(eventType, "eventType");
        Objects.requireNonNull(payloadType, "payloadType");
        Objects.requireNonNull(factory, "factory");

        Registration previous = registrations.putIfAbsent(
                eventType,
                new Registration(payloadType, factory)
        );
        if (previous != null) {
            throw new ExceptionInInitializerError(
                    "Duplicate journal event discriminator: " + eventType
            );
        }
    }

    private record Registration(
            Class<? extends JournalEventObservation> payloadType,
            Function<RawJournalData, ? extends JournalEventObservation> factory
    ) {
        private Registration {
            Objects.requireNonNull(payloadType, "payloadType");
            Objects.requireNonNull(factory, "factory");
        }
    }
}